### ISSUE TITLE
Key not found after being inserted

### ISSUE THREAD

**Issue by 0joshuaolson1** [andy-kimball/arenaskl#3]
The following write-heavy 'benchmark' code nondeterministically breaks with `panic: missing` (you may need to fiddle with the settings at the beginning):
```
package main
import(
  "github.com/andy-kimball/arenaskl"

  "fmt"
)

const arenaSize = 1 << 27
var printEvery65536x_added byte = 4
var procs = 1

func main(){
  printEvery65536x_added--
  for; procs > 1; procs--{
    go run()
  }
  run()
}

var v = make([]byte, 0) // e.g. []byte{4} also works
func run(){
  k := make([]byte, 4)
  var iter arenaskl.Iterator
  iter.Init(arenaskl.NewSkiplist(arenaskl.NewArena(arenaSize)))
  for{
    iter.Add(k, v, 0)
    if !iter.Seek(k){
      panic("missing")
    }
    if k[0] < 255{k[0]++; continue}
    k[0]=0
    if k[1] < 255{k[1]++; continue}
    k[1]=0
    if k[2] < printEvery65536x_added{k[2]++; continue}
    k[2]=0
    fmt.Println(k[3])
    k[3]++
  }
}
```

**Comment by 0joshuaolson1** [comment]
```
$ go version
go version go1.10 linux/amd64
```

**Comment by nvb** [comment]
Thanks for the report @0joshuaolson1! The issue you're observing is because the code is not checking the return value of `iter.Add`. If you add an error check in, you'll notice that before this panic you will always see an [`ErrArenaFull`](https://github.com/andy-kimball/arenaskl/blob/224761e552afe64db9d93004f8d5d3a686b89771/arena.go#L42) error. The error indicates that because the memory arena is full, the key cannot be added to the skiplist. This is described in the [README](https://github.com/andy-kimball/arenaskl#limitations), and is one of the strong tradeoffs the library had to make to acheive its other goals.

**Comment by nvb** [comment]
@andy-kimball I don't have permission to close this issue, but you can feel free to.

**Comment by 0joshuaolson1** [comment]
Sorry for wasting your time. For some reason I thought the behavior was nondeterministic. What a difference `1 << 25 versus 1 << 30` makes. (especially with that metadata overhead?)
